COD/Controllers/RoleController.cs
using BAL.Repositories;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using DAL.DBEntities;
using Newtonsoft.Json;
using DAL.Models.Notifications;

namespace COD.Controllers
{
    public class RoleController : BaseController
    {
        // GET: Role
        public async Task<ActionResult> Index()
        {
            string url = utilityRepository.getBaseUrl() + "role/getAsyncRoles";
            string urlParameter = @"accesstoken=" + HttpUtility.UrlEncode(currentUser.userAccessToken) + "&&roleid";
            var model = await utilityRepository.getAsyncResponse<RoleListResponseVM>(url, urlParameter, false);

            return View(model.Roles);
        }


        public async Task<ActionResult> Detail(int id)
        {
            var model = await getRoleById(id);
            if (model.Code == (int)ResponseCode.Success)
            {
                var role = model.Roles.FirstOrDefault();
                return View("Save", role);
            }

            return Json(new { success = false, msg = model.Message }, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Edit(int id)
        {

            var model = await getRoleById(id);
            if (model.Code == (int)ResponseCode.Success)
            {
                var role = model.Roles.FirstOrDefault();
                return View("Save", role);
            }

            return Json(new { success = false, msg = model.Message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Save()
        {
            return View(new tblRole());
        }

        [HttpPost]
        public async Task<ActionResult> Save(tblRole role)
        {
            bool isSuccess = false;
            string MessageKey = TempKey.FailedMsg.ToString();
            ModelState.Remove("RoleID");
            var err = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => x).ToList();

            if (ModelState.IsValid)
            {
                CreateRoleRequest req = new CreateRoleRequest();
                req.accesstoken = currentUser.userAccessToken;
                req.Role = role;
                string url = utilityRepository.getBaseUrl() + "user/createroleasync";
                var model = await utilityRepository.getAsyncResponse<BaseRespone>(url, JsonConvert.SerializeObject(req), false);
                isSuccess = model.Code == (int)ResponseCode.Success ? true : false;
                MessageKey = isSuccess ? TempKey.SuccessMsg.ToString() : MessageKey;
                TempData[MessageKey] = model.Detail;
                return Json(new { success = isSuccess }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = isSuccess }, JsonRequestBehavior.AllowGet);
        }

        //Permission
        #region Permission
        // GET: Permission

        public ActionResult RolePermission(int? id)
        {
            //getAllPermissions Api Call
            string url = utilityRepository.getBaseUrl() + "role/getAllPermissions";
            string urlParameter = @"accesstoken=" + HttpUtility.UrlEncode(currentUser.userAccessToken) + "&&roleid=" + id.ToString();
            var model = utilityRepository.getResponse<AllPermissionResponseModel>(url, urlParameter, false);
            ViewBag.roleid = id;
            return View(model);
        }

        [HttpPost]
        public JsonResult SavePermission(updatePermissionRequestModel vm)
        {
            bool isSave = false;
            string message = string.Empty;

            vm.accesstoken = currentUser.userAccessToken;
            ModelState.Clear();
            TryValidateModel(vm);
            try
            {
                if (ModelState.IsValid)
                {
                    string url = utilityRepository.getBaseUrl() + "role/updateRolePermission";
                    var model = utilityRepository.getResponse<AllPermissionResponseModel>(url, Newtonsoft.Json.JsonConvert.SerializeObject(vm), true);
                    if (model.Code == (int)ResponseCode.Success)
                    {
                        isSave = true;
                        CacheModel.SysPermissionsViewModelByAPI = null;
                        message = "Permissions updated successfully.";
                        TempData[TempKey.SuccessMsg.ToString()] = message;
                    }
                    else
                    {
                        isSave = false;
                        message = model.Detail;
                        TempData[TempKey.FailedMsg.ToString()] = message;
                    }
                }
            }
            catch (Exception ex)
            {
                isSave = false;
                message = ex.Message;
                TempData[TempKey.FailedMsg.ToString()] = message;
            }

            return Json(new { IsSave = isSave, Message = message }, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region privateMethod
        private async Task<RoleListResponseVM> getRoleById(int id)
        {
            string url = utilityRepository.getBaseUrl() + "role/getAsyncRoles";
            string urlParameter = @"accesstoken=" + HttpUtility.UrlEncode(currentUser.userAccessToken) + "&&roleid=" + id.ToString();
            return await utilityRepository.getAsyncResponse<RoleListResponseVM>(url, urlParameter, false);

        }
        #endregion

    }
}

COD/Views/Role/Index.cshtml
@model List<DAL.DBEntities.tblRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    var thisController = (COD.Controllers.RoleController)ViewContext.Controller;
    string currentControllerName = this.ViewContext.RouteData.Values["controller"].ToString();

    var thisPagePermissions = thisController.currentUser.thisPage.tblPermissions.ToList();   
}

<h2>Role Index</h2>


<div class="row">
    <table class="table table-responsive jqDataTable">
        <thead>
            <tr>
                <td>Role ID</td>
                <td>Role Name</td>
                <td>Is Active</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.RoleID</td>
                        <td>@item.RoleName</td>
                        <td>@item.IsActive</td>
                        <td>
                            @if (thisPagePermissions.Where(x => x.Permission == PermissionEnum.ViewRoleDetail).FirstOrDefault() != null)
                            {
                                <button class="btn btn-default EditRole" _id="@item.RoleID" title="View" actionfor="View"><i class="icon-eye" data-toggle="tooltip" data-placement="right"></i></button>
                            }
                            @*@if (thisPagePermissions.Where(x => x.Permission == PermissionEnum.UpdateRole).FirstOrDefault() != null)
                            {
                                <button class="btn btn-default EditRole" _id="@item.RoleID" title="Edit" actionfor="Edit"><i class="icon-pencil" data-toggle="tooltip" data-placement="right"></i></button>
                            }
                            @if (thisPagePermissions.Where(x => x.Permission == PermissionEnum.DeleteRole).FirstOrDefault() != null)
                            {
                                <button class="btn btn-default DeleteRole" _id="@item.RoleID" title="Delete"><i class="icon-trash" data-toggle="tooltip" data-placement="right"></i></button>
                            }*@
                            @if (thisPagePermissions.Where(x => x.Permission == PermissionEnum.ViewRolePermission).FirstOrDefault() != null)
                            {
                                <button class="btn btn-default Permissions" _id="@item.RoleID" title="Permissions"><i class="icon-key" data-toggle="tooltip" data-placement="right"></i></button>
                            }
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

@section scripts
{

    <script type="text/javascript">


    $(document).ready(function () {
        $('.jqDataTable').DataTable();



        $('body').on("click", ".EditRole,#AddNew", function () {
            var id = $(this).attr('_id');
            var obj = { id: id };

            var title = $(this).attr('actionfor');
            var url = '';
            if (title == "View") {
                url = '@Url.Action("Detail", "Role")';
            }
            else if (title == "Edit") {
                url = '@Url.Action("Edit", "Role")';
            }
            else {
                url = '@Url.Action("Save", "Role")';
                obj = null;
            }



            $.get(url, obj, function (data) {
                debugger;
             //   hideLoader();
                $("#ModalRole").html(data);
                $("#RoleModal").modal('show');
                if (title == "View") {
                    disable_Controls("RoleModal");
                    //Fetched new Modal
                    $("#btnSave").hide();
                }
            });

        });



        $(".Permissions").click(function () {
            var roleid = $(this).attr("_id");
            var url = '@Url.Action("RolePermission", "Role")' + '/' + roleid;
            window.location.replace(url);
        });
    });

    </script>

}

@section modals{
    <div id="ModalRole"></div>
}

COD/Views/Role/RolePermission.cshtml
@model DAL.Models.AllPermissionResponseModel
@{
    ViewBag.Title = "RolePermissions";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var thisController = (COD.Controllers.RoleController)ViewContext.Controller;
    string currentControllerName = this.ViewContext.RouteData.Values["controller"].ToString();

    var thisPagePermissions = thisController.currentUser.thisPage.tblPermissions.ToList();
    bool canManagePermission = thisPagePermissions.Where(x => x.Permission == PermissionEnum.UpdateRolePermission).FirstOrDefault() != null ? true : false;
}

<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <a href='@Url.Action("Index","Role")' class="icon-arrow-left52 position-left"></a>
                <span class="text-semibold">Permission</span> - Manage Permission
                <span class="pull-right">
                    @if (canManagePermission)
                    {
                        <a class="btn btn-primary noloading" id="SaveChanges" _id="0">Save Changes</a>
                    }
                </span>

            </h4>

        </div>
    </div>
    <h4 style="margin-left: 20px;" class="pull-left"><b>Role |</b> @Model.tblRole.RoleName</h4>
</div>

<div class="panel-body">

    <div class="row">

        <div id="divPermissions" class="col-lg-12">

            @{if (Model != null)
                {
                    <div class="table-responsive">
                        <form id="frm_Permission">
                            <div class="box-body">
                                <ul class="nav nav-lg nav-tabs nav-justified no-margin no-border-radius bg-indigo-400 border-top border-top-indigo-300">

                                    @{string active = "active";}

                                    @foreach (var listMod in Model.tblModule)
                                    {
                                        if (listMod.ModuleName.Contains("Complaints & Advisory"))
                                        {
                                            listMod.ModuleName = listMod.ModuleName.Replace("Complaints & Advisory", "Complaints Advisory");
                                        }

                                        <li class="@active"><a href="#@listMod.ModuleName.Replace(" ","")" role="tab" data-toggle="tab">@listMod.ModuleName</a></li>
                                        active = "";



                                    }

                                </ul>
                                <div class="tab-content responsive">

                                    @{active = "active";}
                                    @foreach (var listModule in Model.tblModule)
                                    {
                                        if (listModule.ModuleName.Contains("Complaints & Advisory"))
                                        {
                                            listModule.ModuleName = listModule.ModuleName.Replace("Complaints & Advisory", "Complaints Advisory");
                                        }
                                        if (!listModule.ModuleName.Contains("Dashboard"))
                                        {
                                            if (ViewBag.roleid == 2020 && (listModule.ModuleName.Contains("Security") || listModule.ModuleName.Contains("Setup")))
                                            { }
                                            else
                                            {
                                                <div class="espaciado tab-pane @active" id="@listModule.ModuleName.Replace(" ","")">
                                                    @{active = "";}
                                                    <div class="table-responsive">
                                                        <table id="tbl_@listModule.ModuleName.Replace(" ","")" class="table table-striped table-bordered tblPagePermission" cellspacing="0" width="100%">
                                                            <thead>
                                                                <tr>
                                                                    <th>Page Name</th>
                                                                    <th>Permission</th>

                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                @{int k = 0;}
                                                                @foreach (var listPages in Model.tblPage.Where(x => x.ModuleID == listModule.ModuleID).ToList())
                                                                {

                                                                    <tr class="formItems">
                                                                        <td>

                                                                            @listPages.PageName
                                                                        </td>
                                                                        <td>


                                                                            <div class="row ">
                                                                                @foreach (var permission in Model.tblPermission.Where(x => x.PageID == listPages.PageID).ToList())
                                                                                {

                                                                                    <div class="col-sm-3 inputele">
                                                                                        @Html.Hidden("PermissionID", permission.PermissionID)
                                                                                        @{bool allow = Model.tblRolePermissionJunc.Where(x => x.PermissionID == permission.PermissionID).FirstOrDefault() != null ? true : false;}
                                                                                        <div class="checkbox">
                                                                                            <label>
                                                                                                @Html.CheckBox("Allow", Convert.ToBoolean(allow)) @permission.Permission

                                                                                            </label>
                                                                                        </div>

                                                                                    </div>
                                                                                            }
                                                                            </div>





                                                                        </td>

                                                                    </tr>
                                                                                                k++;
                                                                                            }


                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                                                                                    }
                                                                                                }
                                                                                            }


                                </div>
                            </div>
                        </form>
                    </div>
                                                                                            }
            }

        </div>
    </div>
</div>



@section scripts
{



    <script type="text/javascript">
        $(document).ready(function () {
            $('#SaveChanges').click(function () {

                var rolid = '@ViewBag.roleid';

                $.ajax({
                    url: '@Url.Action("SavePermission", "Role")',
                    type: 'POST',
                    ContentType: 'application/json',
                    dataType: 'json',
                    data: {
                        permissionlist: JSON.stringify(tblToJson2($("#frm_Permission .tblPagePermission tbody tr"))),
                        roleID: rolid
                    },
                    success: function (data) {
                        if (data.IsSave) {
                            window.location.href = "/Role/Index";
                        }
                        else {
                            showMessageAlert("Error", data.Message);
                        }
                    }
                });
            });
        });

    </script>
}

COD/Views/Role/Save.cshtml
@model DAL.DBEntities.tblRole

@{
    Layout = null;
    string postAction = Model != null && Model.RoleID > 0 ? "Edit" : "Save";
}

<script type="text/javascript">
    function RoleSuccess(result) {
        debugger;
        if (result.success) {
            window.location.reload();
        }
        else {
            $('.modal-backdrop').remove();
            $('#RoleModal').modal('show');
        }
    }

</script>

@using (Ajax.BeginForm(postAction, "Role", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "ModalRole", OnSuccess = "RoleSuccess" }, new { @id = "RoleForm" }))
{

    @Html.ValidationSummary(true);
    string formHeading = "New Role";
    if (Model == null || Model.RoleID == 0)
    {

    }
    else
    {

        formHeading = "Role (" + Model.RoleName + ")";
    }

    <div class="modal fade" id="RoleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">     
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header mheader">
                    <h4 class="modal-title mtitle" id="myModalLabel">@formHeading</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                </div>
                <div class="modal-body mbody">
                    <div class="form-horizontal">
                        <div class="form-group fgroup">
                            <label class="control-label">Role Name</label>
                            @Html.HiddenFor(m => m.RoleID, new Dictionary<string, object> { { "data-val", false } })
                            @Html.TextBoxFor(model => model.RoleName, new { @class = "form-control", validate = "Validate", require = "Please Enter Name" })
                            @Html.ValidationMessageFor(model => model.RoleName)
                        </div>


                        <div class="form-group fgroup">
                            <label class="control-label">&nbsp;</label>
                            <div class="checkbox">
                                @Html.CheckBoxFor(model => model.IsActive, new { @class = "chk-col-cyan" })
                                @Html.LabelFor(modle => modle.IsActive, new { @class = "lbl-chk-cyan ch-box-text" })

                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer mfooter">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnSave" class="btn btn-info waves-effect btnSubmit">Submit</button>
                </div>
            </div>
        </div>
    </div>
}


@*<script src="@Url.Content("~/Assets/plugins/foolproof/mvcfoolproof.unobtrusive.min.js")"></script>*@


<script type="text/javascript">
    $(document).ready(function () {
    //  $(".selectpicker").selectpicker();
        
      //  validateModal("RoleForm");

    });
</script>